CREATE DATABASE IF NOT EXISTS `mytest` DEFAULT　CHARACTER SET 'UTF8';
CREATE TABLE IF NOT EXISTS `user`(
id SMALLINT,
username VARCHAR(20),
age TINYINT,
sex ENUM('男'，'女','保密'),
salary FLOAT(8,2),
tel INT,
married TINYINT(1) COMMIT '0未婚，非0已婚'
)ENGINE=INNODB CHARSET=UTF8;